- README.md
Hi Jeremy,
I updated the pdf link to the camera-ready version of our TyDe paper. Moreover I added references to the two extended abstracts about effect handlers appearing in ML Workshop this year.
> Updated the 2016 section

- README.md
Swierstra's paper is useful for developing algebraic effects as effect functors.
See Handlers In Scope (Wu and Hinze) or Fusion for Free (Wu)
> Added Swierstra's datatypes a la carte into list

- README.md
... relevant ESOP 2018 paper by Amr Hany Saleh, Georgios Karachalias, Matija Pretnar, and Tom Schrijvers.
> Adds "Explicit Effect Subtyping" paper

- README.md
I don't intend to make this a daily routine. But I realised the following references were missing:
- Concurrent System Programming with Effect Handlers (TFP'17)
- The full paper version of Eff Directly in OCaml (ML'16)
- The Multicore OCaml abstract about algebraic effects and handlers in OCaml (OCaml'15)
> Add TFP'17 paper, link to ML 2016 post-proceedings paper, and add OCaml effects abstract

- README.md
These two papers recently became available on ACM open access digital library.
> SPLASH 2018 papers

- README.md
This patch adds references to PostScript versions of some of the earlier papers.
(This is a clone of an earlier patch created via the GitHub interface which seems to get stuck on the CI).
> Update paper references

- README.md
Extended version of ICFP 2020 camera ready.
> Update reference to "Effect Handlers, Evidently".

- README.md
This commit replaces the reference to the draft version of "Effect for
Efficiency" with a reference to the extended arxiv version.
> Update "Effects for Efficiency" reference.

- README.md
This commit also includes a few housekeeping fixes:
* GitHub is consistently spelled with capital G and H.
* Remove insignificant trailing whitespace.
> Add a reference to the CUFP'17 tutorial GitHub repository.

- README.md
I appreciate having our paper listed, but it is not yet fully accepted at OOPSLA and I do not want to spread the impression it is. 
For the time being, maybe we can add "conditionally accepted"?
> Add "conditionally accepted"

- README.md
This commit adds two trailing whitespaces to the author line.
> Fix Mycroft et al. (2016) entry.

- README.md
This commit sorts the entries in the Software section (ascending according to the ASCII table).
Also added "Microsoft Research and Inria" as primary authors of F\*.
Also added a DOI for Schuster et al. (2020).
> Sort Software section entries

- README.md
This commit extends the software section with references to an
implementation of Wasm/k and its website. This commit also extends the
2020 paper section with a reference to a DLS'20 paper about Wasm/k.
> Wasm/k references.

- README.md
Paper by Dylan McDermott, Maciej Piróg, and Tarmo Uustalu.
> Degrading Lists (PPDP'20).

- README.md
This commit adds Craig McLaughlin's PhD dissertation to the "Theses
and Dissertations" section.
Also, this commit inserts the often erroneously omitted "The" in the
name "The University of Edinburgh".
Furthermore, for consistency every "PhD thesis" is changed to "PhD
dissertation".
There are two more things: updated the reference for JFP paper "Effect
Handlers via Generalised Continuations", and fixed rendering of links for 
"Degrading Lists".
> Craig McLaughlin's PhD dissertation and other minor fixes.

- README.md
I added the paper "A Complete Normal-Form Bisimilarity for Algebraic Effects and Handlers" by Biernacki and friends from FSCD 2020.
> Add FSCD 2020 paper by Biernacki et al.

- README.md
* Retrofitting Effect Handlers onto OCaml (PLDI 2021) by KC and the present and former OCaml Labs lot.
* Extending Effekt with Bidirectional Effects (MSc dissertation) by Kazuki Niimi.
> Retrofitting Effect Handlers onto OCaml & Kazuki Niimi's MSc dissertation

- README.md
This commit adds Daan Leijen's `libhandler` and `libmprompt` to the
software section. It also restores the alphabetic ordering of the
software list.
> Update software section.

- README.md
The previous PDF link was guarded by a paywall.
> Update PDF link for 'One-shot Algebraic Effects as Coroutines'.

- README.md
- `Contextual Effect Polymorphism` was pointing to `First-class Named Handlers`
- `Design and Implementation of Effect Handlers for Object-Oriented Programming Languages` had broken link so I've changed that to dblp entry
> Fix broken links to papers

- README.md
Caspar -> Casper, see spelling here https://dl.acm.org/doi/abs/10.1145/3571255 or http://casperbp.net/
> Fix spelling error in author name

- README.md
Remove the flaky ACM link for "First Class Dynamic Effect Handlers", which is [causing CI to fail](https://github.com/yallop/effects-bibliography/actions/runs/5755411983/job/15602777330?pr=175)
@daanx, if you have a non-ACM link that we could use instead, it'd be appreciated.
> Remove broken link for "First Class Dynamic Effect Handlers".

- README.md
Add an entry for [Modular probabilistic models via algebraic effects](https://dl.acm.org/doi/pdf/10.1145/3547635) (ICFP 2022) by @min-nguyen, @rolyp, @mengwangoxf, and @zenzike.
> Add "Modular probabilistic models via algebraic effects"

- README.md
> Fix Turbolift formatting (missing 2 spaces)

- README.md
Add
*  [Typed equivalence of labeled effect handlers and labeled delimited control operators](https://prg.is.titech.ac.jp/members/masuhara/papers/ppdp2023.pdf) (PPDP 2023)  
by @kadu-v , @YouyouCong and @masuhar
> Add "Typed equivalence of labeled effect handlers and labeled delimited control operators"

- .github/workflows/checklinks.yml
- .lycheeignore
Switch to [lychee-action](https://github.com/lycheeverse/lychee-action) for checking links.  It's faster, better maintained and much more flexible than the existing script.
This PR also adds some exclusions to the link checking, in the `.lycheeignore` file:
- dl.acm.org links, which often fail due to Cloudflare traps.  (Reviewers should instead check new dl.acm.org links manually before merging.)
- https://www.cs.uoregon.edu/research/summerschool/, which is currently rate-limited
> Switch to lychee-action for checking links

- .lycheeignore
- README.md
Adds:
* OOPSLA'23 paper
* WasmFXtime
* SPLV'22 lecture
In addition, I have made the hyperlink identifiers in the software section more consistent. I have also removed some irrelevant trailing whitespace.
> Updates to paper, software, and tutorial sections

- README.md
and "Category-Graded Algebraic Theories and Effect Handlers", also by @sndtkrh
> Add "Algebraic Effects and Handlers for Arrows" by Takahiro Sanada

- .lycheeignore
- README.md
For the purpose of writing a survey paper, I've started collecting papers on handlers from DBLP. I plan to add interesting missing papers later on, but first, I've done slight white-space changes and added DOIs and DBLP links for most of the papers from 2010 onwards.
> Clean-up & DBLP links

- .lycheeignore
- README.md
I've now gone through all the papers in the list and updated all of those that exist in DBLP (add DOI, BibTeX, fix typos, use official title capitalisation). I think we can consider #8 closed.
> Fix existing and add missing meta-data

- README.md
We also have many more collaborators than the three listed. What is the general strategy here?
> Update Effekt description and URL

- README.md
This pull request adds two of my papers (LMCS'23 and ESOP'23) to the list of publications. It also adds some information to my POPL'21 paper.
> Add two of my papers.

- README.md
This PR adds the interpreter of Fram programming language to the Software list.
> Add Fram programming language
