yallop/effects-bibliography

README.md
Would this be a good way to addres issue #8 ?
=> Add DOI, arxiv, dblp links to some papers.

README.md
* Effect handlers are now in the master branch of Links
* Added Scala Effekt
=> Software section updated

README.md
I have added two recent papers by Daan.
=> Recent papers by Daan

README.md
Hi Jeremy,
I recently stumbled upon Nick Palladinos' library for algebraic effects and handlers in F#. I have added it to the software section.
=> Nick Palladinos' Eff library in F#

README.md
Here's the link I promised last week to the pdf (and the Coq formalisation) of "Handle with Care".
=> Added links to the paper and Coq formalisation for "Handle with Care" (POPL 2018)

README.md
Added Pretnar et al.'s technical report on compilation of algebraic effects and their handlers.
=> Efficient Compilation of Algebraic Effects and Handlers (tech. report)

README.md
Adding pioneering publications on the effect systems in programming languages.
=> Add 1988 papers by David K. Gifford et al.

README.md
I recent stumbled upon this IFL 2017 paper.
=> Adds Handlers for Non-monadic Computations paper

README.md
Add @jirkamarsik and Maxime Amblard's NLCS 2014 paper:
Algebraic Effects and Handlers in Natural Language Interpretation
=> Add "Algebraic Effects and Handlers in Natural Language Interpretation"

README.md
Also removes some insignificant whitespace.
=> Adds Versatile Event Correlation with Algebraic Effects. 

README.md
=> Switch scala-effekt link to GitHub; remove broken link to Effekt paper

README.md
=> Adds 'Shallow Effect Handlers'.

README.md
Hi Jeremy,
I recently stumbled upon some new papers that appeared earlier this year, I have added them to this list. Also, I noticed that your own "Staged Generic Programming" was missing from the list, which I think belongs here; so I added that as well.
Kind regards, Daniel
=> Adds some 2018 papers and your 2017 paper

README.md
Add a link to @andrejbauer's tutorial.
=> Add "What is algebraic about algebraic effects and handlers?"

README.md
Software and paper references for the Pyro programming language.
=> Adds references for Pyro

README.md
Add @ah-saleh's PhD dissertation "Efficient Algebraic Effect Handlers" (March 2019)
=> Add 'Efficient Algebraic Effect Handlers'

README.md
Adds a couple of papers about effect systems for lazy languages, interaction between effects and coeffects, relationship between effects and sessions, and more.
=> Recent-ish papers on effect systems

README.md
A paper to be presented at FSCD 2019
=> Add "Typed equivalence of effect handlers and delimited control"

README.md
A recent paper by Biernacki et al. (LMCS, 2019).
=> Bisimulations for Delimited-Control Operators.

README.md
This patch adds two papers from MPC 2019 to the list:
- A Hierarchy of Monadic Effects for Program Verification using Equational Reasoning, by Reynald Affeldt, David Nowak, and Takafumi Saikawa
- Handling Local State with Global State, by Koen Pauwels, Tom Schrijvers, and Shin-Cheng Mu
=> A couple of relevant papers from MPC 2019.

README.md
Change url https://github.com/andrejbauer/effects-rosetta-stone -> https://github.com/effect-handlers/effects-rosetta-stone.
=> Update the link to the effects rosetta stone.

README.md
Adds a reference to the JFP edition of "On the expressive power of
user-defined effects: effect handlers, monadic reflection, delimited
control".
=> JFP edition of Forster et al.

README.md
Add @dhil's, @slindley's & @bobatkey's 2020 JFP paper.
=> Add "Effect handlers via generalised continuations"

README.md
Add @b-studios's, @phischu's and @klauso's JFP 2020 paper.
=> Add "Effekt: Capability-passing style for type- and effect-safe, extensible effect handlers in Scala"

README.md
=> Added some recent papers

README.md
Current link leads to 403 error
=> Correct broken link to Effekt paper

README.md
* **Signature restriction for polymorphic algebraic effects**  
by Taro Sekiyama, Takeshi Tsukada, and Atsushi Igarashi  
* **Effects for Efficiency: Asymptotic Speedup with First-Class Control**  
by Daniel Hillerström, Sam Lindley, and John Longley  
* **Effect Handlers, Evidently**  
by Ningning Xie, Jonathan Immanuel Brachthäuser, Daniel Hillerström, Philipp Schuster, and Daan Leijen  
* **Compiling Effect Handlers in Capability-Passing Style**  
by Philipp Schuster, Jonathan Immanuel Brachthäuser, and Klaus Ostermann
=> Add some ICFP 2020 papers

README.md
Add "Generalized Monoidal Effects And Handlers" by @rubenpieters, Exequiel Rivas, and Tom Schrijvers
=> Add "Generalized Monoidal Effects And Handlers"

README.md
This commit extends the "Software" and "Papers 2020" sections with references to the
"Effekt Language".
=> Add Effekt Language to list of software.

README.md
Please see issue https://github.com/yallop/effects-bibliography/issues/8 and my comment  https://github.com/yallop/effects-bibliography/issues/8#issuecomment-677540162
=> Bibtex entries for papers with DBLP links

README.md
This commit adds a DOI reference and updates the PDF reference to
point to the published version.
=> Update Kawahara and Kameyama (2020) entry.

README.md
This commit adds a FoSSaCS'19 paper by Cristina Matache and Sam
Staton to the 2019 paper section.
=> Add "A Sound and Complete Logic for Algebraic Effects" by Matache and Staton.

README.md
This commit adds an entry for Æff to the software section.
=> Æff interpreter reference.

README.md
=> Fix a minor inconsistency

README.md
Leo Poulson's MSc dissertation.
=> Add 'Asynchronous Effect Handling'.

README.md
=> OOPSLA 2020 paper

README.md
Add @DeVilhena-Paulo and @fpottier's POPL'21 paper:
* **A Separation Logic for Effect Handlers** (POPL 2021)  
by Paulo Emílio de Vilhena and  François Pottier  
([pdf](http://cambium.inria.fr/~fpottier/publis/de-vilhena-pottier-sleh.pdf))
=> Add "A Separation Logic for Effect Handlers"

README.md
... by Gorinova et al. @ ICML 2020.
=> Automatic Reparameterisation of Probabilistic Programs

README.md
by me. Final version written in 2019; final approval in June.
=> Add "Defined Algebraic Operations"

README.md
This commit adds
* Letan et al. (2020).
* Kiselyov et al. (2020)
This commit modifies (i.e. updates)
* Ahman and Pretnar (2021)
* Brachthäuser et al (2020)
=> New stuff and housekeeping

README.md
Paper by Youyou Cong, Chiaki Ishio, Kaho Honda, and Kenichi Asai.
=> A Functional Abstraction of Typed Invocation Contexts (FSCD 2021)

README.md
"Higher-Order Asynchronous Effects" by Danel Ahman, Matija Pretnar, and Janez Radešček.
=> Another extended abstract from HOPE.

README.md
Adds my own extended abstract.
=> ML Family Workshop 2021 abstract

README.md
This commit adds my own thesis to the "Theses and Dissertations" section.
=> Foundations for Programming and Implementing Effect Handlers

README.md
The commits in this patch should be squashed before merge.
=> Some 2022 papers

README.md
Add @juliangrove and @jyp's [Algebraic effects for extensible dynamic semantics](https://semanticsarchive.net/Archive/TMxNGE3M/algebraic.pdf)
=> Add "Algebraic effects for extensible dynamic semantics"

README.md
This commit extends the tutorial section with the lecture series on effect handler oriented programming that was delivered by Sam Lindley at OPLSS earlier this year.
=> Effect handler oriented programming at OPLSS

README.md
=> Add Turbolift

README.md
Add paper "Towards a Reflection for Effect Handlers" (PEPM 2023).
=> Add papers: "Hefty Algebras" and "Towards a Reflection for Effect Handlers"

README.md
- [*A General Fine-Grained Reduction Theory for Effect Handlers*](https://dl.acm.org/doi/pdf/10.1145/3607848)  
by Filip Sieczkowski, Mateusz Pyzik, and Dariusz Biernacki
- [*With or Without You: Programming with Effect Exclusion*](https://dl.acm.org/doi/pdf/10.1145/3607846)  
by Matthew Lutze (@mlutze), Magnus Madsen (@magnus-madsen), Philipp Schuster, and Jonathan Immanuel Brachthäuser (@b-studios)
=> Add a couple of ICFP 2023 papers

README.md
New PR for the changes from the auto-closed (and unreopenable) #182
=> Add "From Capabilities to Regions"

README.md
Fix [CI failure](https://github.com/yallop/effects-bibliography/actions/runs/7397158853/job/20123758614?pr=186) arising from broken links
=> Update links to papers from the Tokyo Institute of Technology PRG.

README.md
Add [Active Objects Based on Algebraic Effects](https://link.springer.com/chapter/10.1007/978-3-031-51060-1_1) (by Martin Andrieux, @lhenrio and @Drup)
=> Add "Active Objects Based on Algebraic Effects"

README.md
Adds my recently accepted JFP paper on asymptotic speedup with effect handlers.
=> JFP'24 paper

README.md
The repository is looking at all possible effects in C++.
=> Add https://github.com/okeuday/effects repo

README.md
This PR adds the Flix programming language to the software list and a recent paper to the papers list.
=> add Flix and Associated Effects

README.md
=> Remove broken link to "Automatic Reparameterisation in Probabilistic Programming"

README.md
Add:
* **Signature restriction for polymorphic algebraic effects** (JFP 2024)  
by Taro Sekiyama, Takeshi Tsukada, and Atsushi Igarashi  
([doi](https://doi.org/10.1017/S0956796824000054)) ([dblp](https://dblp.org/rec/journals/jfp/SekiyamaTI24.html)) ([bibtex](https://dblp.org/rec/journals/jfp/SekiyamaTI24.html?view=bibtex)) ([pdf](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/1FCD90F7590C031791DBE08DCD65CED5/S0956796824000054a.pdf/signature_restriction_for_polymorphic_algebraic_effects.pdf))
* **Parallel Algebraic Effect Handlers** (ICFP 2024)  
by Ningning Xie, Daniel D. Johnson, Dougal Maclaurin, and Adam Paszke  
([doi](https://doi.org/10.1145/3674651)) ([dblp](https://dblp.org/rec/journals/pacmpl/Xie0MP24.html)) …
=> Add a dozen papers and dissertations from 2024

README.md
Add @oliverjgoldstein's dissertation (cc @ohad)
=> Add Oliver Goldstein's MSc dissertation
